### ISSUE TITLE
Error:[string "--Hello!

### ISSUE THREAD

**Issue by keboramli** [xAranaktu/FIFA-21-CM-Cheat-Table#12]
**,,,,"]:11:.\lua/imports/CheatTableManager.lua:713:attempt to index a nil value (field 'flags')**

Could please help me with this issue? It was working really fine before this but now this issue came out from nowhere. Thanks

**Comment by xAranaktu** [comment]
Delete `offsets.ini` and `config.ini` from `Documents\FIFA 21\Cheat Table\data`

**Comment by keboramli** [comment]
Hi. I already deleted both but its still not working.
![sasaass](https://user-images.githubusercontent.com/78271976/106363559-2c893100-6364-11eb-9072-f8e401f2e8d4.png)
