### ISSUE TITLE
Get best grade training when simulating on Manager mode

### ISSUE THREAD

**Issue by JoseLuisRuedaA** [xAranaktu/FIFA-21-CM-Cheat-Table#14]
By default if you simulate the training you will get "D" on all trainings unless you play it before and get "A". This occurs every time you start a new manager mode.
Could be possible to get "A" from the beggining?

**Comment by xAranaktu** [comment]
No.
https://github.com/xAranaktu/FIFA-21-CM-Cheat-Table/wiki/Frequently-asked-questions
