### ISSUE TITLE
Why the change be reset when match finish？

### ISSUE THREAD

**Issue by BarrettGuaN** [xAranaktu/FIFA-21-CM-Cheat-Table#16]
Every change is be reset before i played one match in MyCareer

**Comment by xAranaktu** [comment]
Because game has copy of old player in memory which overwrites your changes. This have been explained billion of times already. There is workaround for it described on [wiki](https://github.com/xAranaktu/FIFA-21-CM-Cheat-Table/wiki/Editing-Player).
