### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by rahul3103** [xAranaktu/FIFA-21-CM-Cheat-Table#17]
Can you write a tutorial or explain how do you read or update squad file? It will be great help if you can explain Thanks

**Comment by xAranaktu** [comment]
Use [RDBM 21](https://downloads.fifa-infinity.com/fifa-21/revolution-db-master-21/)

**Comment by rahul3103** [comment]
@xAranaktu Hey, I was asking programmatically how do you read the FIFA DB. Can I use python or JavaScript to read the Squad file
