### ISSUE TITLE
Time Of Day Script Error ?

### ISSUE THREAD

**Issue by 3mr3blgn** [xAranaktu/FIFA-21-CM-Cheat-Table#20]
![Adsız](https://user-images.githubusercontent.com/82727676/115123669-c60cca00-9fc6-11eb-8763-6ad8337134b5.png)

**Comment by 3mr3blgn** [comment]
@xAranaktu All Script Files Are Working It's Just A Problem How Can I Solve It Would Be Appreciated If You Can Help?

**Comment by xAranaktu** [comment]
Fixed in [v21.1.2.0](https://github.com/xAranaktu/FIFA-21-CM-Cheat-Table/releases/tag/v21.1.2.0)
