### ISSUE TITLE
BUG: Player's attributes restore after play a match!

### ISSUE THREAD

**Issue by thangld322** [xAranaktu/FIFA-21-CM-Cheat-Table#8]
I'm using Cheat table version 21.1.1.8 and Cheat engine version 6.81 to edit Rooney in career mode following this guide https://github.com/xAranaktu/FIFA-21-CM-Cheat-Table/wiki/Editing-Player#editing-player-through-gui 
I changed his potential, age, and attributes then click Apply. Then, I played a match and after that match, his attributes returned as before while his potential and age stayed!

**Comment by xAranaktu** [comment]
Works fine for me.

**Comment by David1016** [comment]
edit before the game which your player‘s attributes is going to change by itself
